services:
  # Customer support bot
  # Uses native Ollama installation via host.docker.internal
  support-bot:
    build: .
    ports:
      - "2024:2024"
    environment:
      # Connect to native Ollama running on host machine
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - ./storage:/app/storage
      - ./src:/app/src
      - ./data:/app/data
    restart: unless-stopped
